Testing 06

diff --git a/.github/workflows/health-check.yml b/.github/workflows/health-check.yml
--- a/.github/workflows/health-check.yml
+++ b/.github/workflows/health-check.yml
@@ -24,7 +24,7 @@ jobs:
             - name: Curl to health check and Print Passed or failed
               run: |
                 sleep 5
-                curl -f  http://localhost:3000/health && echo "Health Check Passed" || {echo "Health Check failed"; exit 1}
+                curl -f  http://localhost:3000/health && echo "Health Check Passed" || { echo "Health Check failed"; exit 1; }
 
             - name: Stop and remove the container
               run: docker compose down
